(function(){
    var defaultVariables = ["speechSynthesis","caches","localStorage","sessionStorage","webkitStorageInfo","indexedDB","webkitIndexedDB","ondeviceorientationabsolute","ondeviceorientation","ondevicemotion","crypto","postMessage","blur","focus","close","stop","onunhandledrejection","onrejectionhandled","open","alert","confirm","applicationCache","performance","prompt","onunload","onstorage","onpopstate","print","onpageshow","onpagehide","ononline","requestAnimationFrame","onoffline","onmessage","onlanguagechange","onhashchange","cancelAnimationFrame","onbeforeunload","onwaiting","onvolumechange","captureEvents","ontoggle","ontimeupdate","onsuspend","releaseEvents","onsubmit","onstalled","onshow","getComputedStyle","onselect","onseeking","matchMedia","onseeked","onscroll","onresize","moveTo","onreset","onratechange","onprogress","moveBy","onplaying","onplay","onpause","resizeTo","onmousewheel","onmouseup","onmouseover","onmouseout","resizeBy","onmousemove","onmouseleave","onmouseenter","getSelection","onmousedown","onloadstart","onloadedmetadata","find","onloadeddata","onload","onkeyup","getMatchedCSSRules","onkeypress","onkeydown","webkitRequestAnimationFrame","oninvalid","oninput","onfocus","onerror","webkitCancelAnimationFrame","onended","onemptied","ondurationchange","webkitCancelRequestAnimationFrame","ondrop","ondragstart","btoa","ondragover","ondragleave","ondragenter","atob","ondragend","ondrag","ondblclick","oncuechange","setTimeout","oncontextmenu","onclose","clearTimeout","onclick","onchange","oncanplaythrough","setInterval","oncanplay","oncancel","onblur","onabort","clearInterval","createImageBitmap","requestIdleCallback","cancelIdleCallback","scroll","scrollTo","scrollBy","fetch","webkitRequestFileSystem","webkitResolveLocalFileSystemURL","openDatabase","external","chrome","console","define","global","WebUIListener","cr","ntp","loadTimeData","LoadTimeData","ProcessingRoot","i18nTemplate","b","bowserVariableList","isSecureContext","onwheel","onwebkittransitionend","onwebkitanimationstart","onwebkitanimationiteration","onwebkitanimationend","ontransitionend","onsearch","onanimationstart","onanimationiteration","onanimationend","styleMedia","defaultstatus","defaultStatus","screenTop","screenLeft","clientInformation","devicePixelRatio","outerHeight","outerWidth","screenY","screenX","pageYOffset","scrollY","pageXOffset","scrollX","innerHeight","innerWidth","screen","navigator","frameElement","parent","opener","top","length","frames","closed","status","toolbar","statusbar","scrollbars","personalbar","menubar","locationbar","history","location","name","document","self","window"];
    var globalVariablesList = [];

    for ( var propertyValue in window ) { 
        if ( !defaultVariables.includes( propertyValue ) ) {
            if ( window.hasOwnProperty( propertyValue ) ) {
                globalVariablesList.push( propertyValue );
            }
        }
    }
    window.globalVariablesList = globalVariablesList;
})();